language: node_js

sudo: false

matrix:
  include:
    - node_js: 7
      script:
        - npm run-script danger
        - npm run-script coverage
      after_script:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

node_js:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

notifications:
  email: false
